-- ====================================
-- SQL SCHEMA COMPLETO - PARTE 2
-- Notification, Risk, Payments, Support, etc
-- ====================================

-- ========== NOTIFICATION-SERVICE ==========
CREATE TABLE IF NOT EXISTS notification_templates (
    id VARCHAR(36) PRIMARY KEY,
    tenant_id VARCHAR(255),
    code VARCHAR(100) NOT NULL,
    channel VARCHAR(50) NOT NULL,
    language VARCHAR(10) NOT NULL,
    subject VARCHAR(500) NOT NULL,
    body TEXT NOT NULL,
    html_body TEXT,
    category VARCHAR(50),
    is_active BOOLEAN DEFAULT TRUE,
    variables TEXT,
    created_by VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_by VARCHAR(255),
    updated_at TIMESTAMP,
    INDEX idx_template_code (code),
    INDEX idx_template_channel (channel),
    UNIQUE KEY unique_template (tenant_id, code, channel, language)
);

CREATE TABLE IF NOT EXISTS notification_history (
    id VARCHAR(36) PRIMARY KEY,
    tenant_id VARCHAR(255) NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    channel VARCHAR(50) NOT NULL,
    template_code VARCHAR(100) NOT NULL,
    subject VARCHAR(500),
    body TEXT,
    recipient VARCHAR(255),
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    sent_at TIMESTAMP,
    delivered_at TIMESTAMP,
    failed_at TIMESTAMP,
    provider VARCHAR(50),
    external_id VARCHAR(255),
    error_message TEXT,
    retry_count INT DEFAULT 0,
    metadata TEXT,
    INDEX idx_notification_user (user_id),
    INDEX idx_notification_status (status),
    INDEX idx_notification_created (created_at)
);

CREATE TABLE IF NOT EXISTS notification_preferences (
    id VARCHAR(36) PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL UNIQUE,
    tenant_id VARCHAR(255) NOT NULL,
    email_enabled BOOLEAN DEFAULT TRUE,
    sms_enabled BOOLEAN DEFAULT TRUE,
    push_enabled BOOLEAN DEFAULT TRUE,
    in_app_enabled BOOLEAN DEFAULT TRUE,
    transactional_enabled BOOLEAN DEFAULT TRUE,
    marketing_enabled BOOLEAN DEFAULT FALSE,
    alerts_enabled BOOLEAN DEFAULT TRUE,
    promotions_enabled BOOLEAN DEFAULT FALSE,
    quiet_hours_start VARCHAR(5),
    quiet_hours_end VARCHAR(5),
    digest_frequency VARCHAR(20),
    updated_at TIMESTAMP,
    INDEX idx_preference_user (user_id)
);

-- ========== RISK-SERVICE ==========
CREATE TABLE IF NOT EXISTS risk_rules (
    id VARCHAR(36) PRIMARY KEY,
    tenant_id VARCHAR(255),
    name VARCHAR(255) NOT NULL,
    description TEXT,
    rule_type VARCHAR(50) NOT NULL,
    action VARCHAR(50) NOT NULL,
    priority INT NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    conditions TEXT,
    min_amount DECIMAL(15,2),
    max_amount DECIMAL(15,2),
    max_transactions_per_minute INT,
    max_transactions_per_hour INT,
    max_transactions_per_day INT,
    risk_score_threshold INT,
    target_user_segments TEXT,
    target_merchant_categories TEXT,
    created_by VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_by VARCHAR(255),
    updated_at TIMESTAMP,
    INDEX idx_rule_type (rule_type),
    INDEX idx_rule_priority (priority),
    INDEX idx_rule_active (is_active)
);

CREATE TABLE IF NOT EXISTS risk_assessments (
    id VARCHAR(36) PRIMARY KEY,
    tenant_id VARCHAR(255) NOT NULL,
    transaction_id VARCHAR(255) NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    merchant_id VARCHAR(255),
    risk_score INT NOT NULL,
    risk_level VARCHAR(20) NOT NULL,
    decision VARCHAR(50) NOT NULL,
    risk_factors TEXT,
    triggered_rules TEXT,
    velocity_score INT,
    location_score INT,
    device_score INT,
    behavioral_score INT,
    ml_score INT,
    ip_address VARCHAR(45),
    device_fingerprint VARCHAR(255),
    location VARCHAR(100),
    user_agent TEXT,
    user_transaction_count INT,
    recent_declined_count INT,
    assessed_at TIMESTAMP NOT NULL,
    processing_time_ms BIGINT,
    metadata TEXT,
    INDEX idx_assessment_transaction (transaction_id),
    INDEX idx_assessment_user (user_id),
    INDEX idx_assessment_decision (decision),
    INDEX idx_assessment_date (assessed_at)
);

CREATE TABLE IF NOT EXISTS blocklists (
    id VARCHAR(36) PRIMARY KEY,
    tenant_id VARCHAR(255),
    list_type VARCHAR(50) NOT NULL,
    value VARCHAR(500) NOT NULL,
    reason VARCHAR(100) NOT NULL,
    status VARCHAR(50) NOT NULL,
    severity VARCHAR(20),
    expires_at TIMESTAMP,
    notes TEXT,
    related_transaction_ids TEXT,
    related_user_id VARCHAR(255),
    created_by VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    removed_by VARCHAR(255),
    removed_at TIMESTAMP,
    INDEX idx_blocklist_type (list_type),
    INDEX idx_blocklist_value (value),
    INDEX idx_blocklist_status (status)
);

CREATE TABLE IF NOT EXISTS user_risk_profiles (
    id VARCHAR(36) PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL UNIQUE,
    tenant_id VARCHAR(255) NOT NULL,
    current_risk_score INT NOT NULL,
    risk_level VARCHAR(20) NOT NULL,
    total_transactions INT DEFAULT 0,
    approved_transactions INT DEFAULT 0,
    declined_transactions INT DEFAULT 0,
    chargeback_count INT DEFAULT 0,
    dispute_count INT DEFAULT 0,
    usual_locations TEXT,
    usual_devices TEXT,
    usual_merchant_categories TEXT,
    usual_transaction_times TEXT,
    usual_transaction_days TEXT,
    has_reached_daily_limit BOOLEAN DEFAULT FALSE,
    has_reached_monthly_limit BOOLEAN DEFAULT FALSE,
    is_new_user BOOLEAN DEFAULT TRUE,
    has_suspicious_activity BOOLEAN DEFAULT FALSE,
    requires_manual_review BOOLEAN DEFAULT FALSE,
    first_transaction_at TIMESTAMP,
    last_transaction_at TIMESTAMP,
    last_risk_assessment_at TIMESTAMP,
    updated_at TIMESTAMP,
    INDEX idx_risk_profile_user (user_id),
    INDEX idx_risk_level (risk_level)
);

-- ========== PAYMENTS-ORCHESTRATOR ==========
CREATE TABLE IF NOT EXISTS payment_orchestrations (
    id VARCHAR(36) PRIMARY KEY,
    tenant_id VARCHAR(255) NOT NULL,
    transaction_id VARCHAR(255) NOT NULL UNIQUE,
    user_id VARCHAR(255) NOT NULL,
    merchant_id VARCHAR(255),
    type VARCHAR(50) NOT NULL,
    amount DECIMAL(15,2) NOT NULL,
    currency VARCHAR(3) DEFAULT 'BRL',
    state VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    completed_steps TEXT,
    pending_steps TEXT,
    payment_method VARCHAR(50),
    wallet_type VARCHAR(50),
    card_id VARCHAR(36),
    risk_service_response TEXT,
    authorization_response TEXT,
    acquirer_response TEXT,
    settlement_response TEXT,
    idempotency_key VARCHAR(255) UNIQUE,
    retry_count INT DEFAULT 0,
    max_retries INT DEFAULT 3,
    circuit_breaker_open BOOLEAN DEFAULT FALSE,
    circuit_breaker_opened_at TIMESTAMP,
    initiated_at TIMESTAMP NOT NULL,
    validated_at TIMESTAMP,
    authorized_at TIMESTAMP,
    completed_at TIMESTAMP,
    failed_at TIMESTAMP,
    error_code VARCHAR(100),
    error_message TEXT,
    failed_step VARCHAR(100),
    compensation_required BOOLEAN DEFAULT FALSE,
    compensation_completed BOOLEAN DEFAULT FALSE,
    compensation_actions TEXT,
    metadata TEXT,
    INDEX idx_payment_transaction (transaction_id),
    INDEX idx_payment_state (state),
    INDEX idx_payment_status (status),
    INDEX idx_payment_initiated (initiated_at)
);

CREATE TABLE IF NOT EXISTS idempotency_records (
    id VARCHAR(36) PRIMARY KEY,
    idempotency_key VARCHAR(255) NOT NULL UNIQUE,
    resource_type VARCHAR(50) NOT NULL,
    resource_id VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL,
    request_body TEXT,
    response_body TEXT,
    http_status INT,
    created_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP,
    INDEX idx_idempotency_key (idempotency_key),
    INDEX idx_idempotency_expires (expires_at)
);

-- ========== SUPPORT-SERVICE ==========
CREATE TABLE IF NOT EXISTS support_tickets (
    id VARCHAR(36) PRIMARY KEY,
    tenant_id VARCHAR(255) NOT NULL,
    ticket_number VARCHAR(50) NOT NULL UNIQUE,
    user_id VARCHAR(255) NOT NULL,
    user_name VARCHAR(255),
    user_email VARCHAR(255),
    subject VARCHAR(500) NOT NULL,
    description TEXT NOT NULL,
    category VARCHAR(100) NOT NULL,
    priority VARCHAR(20) NOT NULL,
    status VARCHAR(50) NOT NULL,
    assigned_to VARCHAR(255),
    assigned_team VARCHAR(100),
    sla_deadline TIMESTAMP,
    sla_breach BOOLEAN DEFAULT FALSE,
    resolution TEXT,
    resolved_at TIMESTAMP,
    resolved_by VARCHAR(255),
    closed_at TIMESTAMP,
    closed_by VARCHAR(255),
    customer_rating INT,
    customer_feedback TEXT,
    related_transaction_id VARCHAR(255),
    related_entity_type VARCHAR(100),
    related_entity_id VARCHAR(255),
    tags TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    INDEX idx_ticket_status (status),
    INDEX idx_ticket_user (user_id),
    INDEX idx_ticket_assigned (assigned_to),
    INDEX idx_ticket_created (created_at)
);

CREATE TABLE IF NOT EXISTS ticket_messages (
    id VARCHAR(36) PRIMARY KEY,
    ticket_id VARCHAR(36) NOT NULL,
    author_id VARCHAR(255) NOT NULL,
    author_type VARCHAR(50) NOT NULL,
    author_name VARCHAR(255),
    message TEXT NOT NULL,
    is_internal BOOLEAN DEFAULT FALSE,
    attachments TEXT,
    created_at TIMESTAMP NOT NULL,
    INDEX idx_message_ticket (ticket_id),
    INDEX idx_message_created (created_at)
);

CREATE TABLE IF NOT EXISTS knowledge_base_articles (
    id VARCHAR(36) PRIMARY KEY,
    tenant_id VARCHAR(255),
    title VARCHAR(500) NOT NULL,
    content TEXT NOT NULL,
    category VARCHAR(100) NOT NULL,
    subcategory VARCHAR(100),
    tags TEXT,
    status VARCHAR(50) NOT NULL,
    slug VARCHAR(500),
    meta_description VARCHAR(500),
    view_count INT DEFAULT 0,
    helpful_count INT DEFAULT 0,
    not_helpful_count INT DEFAULT 0,
    language VARCHAR(10) DEFAULT 'pt-BR',
    created_by VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_by VARCHAR(255),
    updated_at TIMESTAMP,
    published_at TIMESTAMP,
    INDEX idx_article_status (status),
    INDEX idx_article_category (category),
    INDEX idx_article_slug (slug)
);

-- Continua parte 3...
