-- ====================================
-- SQL SCHEMA COMPLETO - LOOP ITERATION
-- Criado: 2026-01-14
-- Todas as entidades implementadas
-- ====================================

-- ========== MERCHANT-BFF ==========
CREATE TABLE IF NOT EXISTS terminals (
    id VARCHAR(36) PRIMARY KEY,
    merchant_id VARCHAR(255) NOT NULL,
    terminal_code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL,
    serial_number VARCHAR(100),
    model VARCHAR(100),
    location VARCHAR(255),
    store_id VARCHAR(36),
    registered_at TIMESTAMP NOT NULL,
    last_activity_at TIMESTAMP,
    software_version VARCHAR(50),
    ip_address VARCHAR(45),
    daily_limit DECIMAL(15,2),
    transaction_limit DECIMAL(15,2),
    nfc_enabled BOOLEAN DEFAULT TRUE,
    qr_code_enabled BOOLEAN DEFAULT TRUE,
    offline_enabled BOOLEAN DEFAULT FALSE,
    created_by VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_by VARCHAR(255),
    updated_at TIMESTAMP,
    INDEX idx_merchant_terminals (merchant_id),
    INDEX idx_terminal_status (status)
);

CREATE TABLE IF NOT EXISTS operators (
    id VARCHAR(36) PRIMARY KEY,
    merchant_id VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    cpf VARCHAR(11) NOT NULL UNIQUE,
    phone VARCHAR(20) NOT NULL,
    status VARCHAR(50) NOT NULL,
    role VARCHAR(50) NOT NULL,
    can_process_payments BOOLEAN DEFAULT TRUE,
    can_issue_refunds BOOLEAN DEFAULT FALSE,
    can_manage_terminals BOOLEAN DEFAULT FALSE,
    can_view_reports BOOLEAN DEFAULT FALSE,
    assigned_terminal_id VARCHAR(36),
    current_shift_id VARCHAR(36),
    created_by VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_by VARCHAR(255),
    updated_at TIMESTAMP,
    last_login_at TIMESTAMP,
    INDEX idx_merchant_operators (merchant_id)
);

CREATE TABLE IF NOT EXISTS shifts (
    id VARCHAR(36) PRIMARY KEY,
    merchant_id VARCHAR(255) NOT NULL,
    operator_id VARCHAR(36) NOT NULL,
    terminal_id VARCHAR(36) NOT NULL,
    status VARCHAR(50) NOT NULL,
    opened_at TIMESTAMP NOT NULL,
    closed_at TIMESTAMP,
    initial_cash DECIMAL(15,2) DEFAULT 0,
    final_cash DECIMAL(15,2),
    total_sales DECIMAL(15,2),
    total_refunds DECIMAL(15,2),
    transaction_count INT DEFAULT 0,
    cash_difference DECIMAL(15,2),
    notes TEXT,
    reconciled BOOLEAN DEFAULT FALSE,
    reconciled_at TIMESTAMP,
    reconciled_by VARCHAR(255),
    INDEX idx_merchant_shifts (merchant_id),
    INDEX idx_operator_shifts (operator_id)
);

CREATE TABLE IF NOT EXISTS merchant_transactions (
    id VARCHAR(36) PRIMARY KEY,
    merchant_id VARCHAR(255) NOT NULL,
    terminal_id VARCHAR(36) NOT NULL,
    operator_id VARCHAR(36),
    shift_id VARCHAR(36),
    type VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    transaction_id VARCHAR(255) NOT NULL UNIQUE,
    amount DECIMAL(15,2) NOT NULL,
    currency VARCHAR(3) DEFAULT 'BRL',
    payment_method VARCHAR(50),
    wallet_type VARCHAR(50),
    user_id VARCHAR(255),
    user_name VARCHAR(255),
    masked_card_number VARCHAR(20),
    created_at TIMESTAMP NOT NULL,
    processed_at TIMESTAMP,
    authorization_code VARCHAR(50),
    nsu VARCHAR(50),
    receipt_url VARCHAR(500),
    metadata TEXT,
    INDEX idx_merchant_transactions (merchant_id),
    INDEX idx_transaction_date (created_at)
);

CREATE TABLE IF NOT EXISTS transfers (
    id VARCHAR(36) PRIMARY KEY,
    merchant_id VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    amount DECIMAL(15,2) NOT NULL,
    currency VARCHAR(3) DEFAULT 'BRL',
    bank_code VARCHAR(10) NOT NULL,
    account_number VARCHAR(50) NOT NULL,
    account_type VARCHAR(20) NOT NULL,
    account_holder_name VARCHAR(255),
    account_holder_document VARCHAR(20),
    requested_at TIMESTAMP NOT NULL,
    scheduled_for TIMESTAMP,
    processed_at TIMESTAMP,
    completed_at TIMESTAMP,
    settlement_id VARCHAR(36),
    external_id VARCHAR(255),
    fee DECIMAL(15,2) DEFAULT 0,
    net_amount DECIMAL(15,2),
    retry_count INT DEFAULT 0,
    last_error TEXT,
    notes TEXT,
    INDEX idx_merchant_transfers (merchant_id),
    INDEX idx_transfer_status (status)
);

-- ========== EMPLOYER-BFF ==========
CREATE TABLE IF NOT EXISTS employees (
    id VARCHAR(36) PRIMARY KEY,
    employer_id VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    cpf VARCHAR(11) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(20) NOT NULL,
    status VARCHAR(50) NOT NULL,
    department_id VARCHAR(36),
    position VARCHAR(255),
    cost_center VARCHAR(100),
    user_id VARCHAR(255),
    plan_id VARCHAR(36),
    hire_date TIMESTAMP NOT NULL,
    termination_date TIMESTAMP,
    benefits_enabled BOOLEAN DEFAULT TRUE,
    address_line1 VARCHAR(255),
    address_line2 VARCHAR(255),
    city VARCHAR(100),
    state VARCHAR(50),
    zip_code VARCHAR(20),
    created_by VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_by VARCHAR(255),
    updated_at TIMESTAMP,
    INDEX idx_employer_employees (employer_id),
    INDEX idx_employee_status (status)
);

CREATE TABLE IF NOT EXISTS departments (
    id VARCHAR(36) PRIMARY KEY,
    employer_id VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(50),
    description TEXT,
    manager_id VARCHAR(36),
    parent_department_id VARCHAR(36),
    cost_center VARCHAR(100),
    status VARCHAR(50) NOT NULL,
    created_by VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_by VARCHAR(255),
    updated_at TIMESTAMP,
    INDEX idx_employer_departments (employer_id)
);

CREATE TABLE IF NOT EXISTS expense_approvals (
    id VARCHAR(36) PRIMARY KEY,
    employer_id VARCHAR(255) NOT NULL,
    employee_id VARCHAR(36) NOT NULL,
    expense_id VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL,
    amount DECIMAL(15,2) NOT NULL,
    currency VARCHAR(3) DEFAULT 'BRL',
    status VARCHAR(50) NOT NULL,
    description TEXT,
    category VARCHAR(100),
    receipt_url VARCHAR(500),
    metadata TEXT,
    approver_ids TEXT,
    current_approver_id VARCHAR(255),
    approved_at TIMESTAMP,
    approved_by VARCHAR(255),
    approval_notes TEXT,
    rejected_at TIMESTAMP,
    rejected_by VARCHAR(255),
    rejection_reason TEXT,
    submitted_at TIMESTAMP NOT NULL,
    processed_at TIMESTAMP,
    INDEX idx_employer_approvals (employer_id),
    INDEX idx_approval_status (status),
    INDEX idx_pending_approver (current_approver_id)
);

CREATE TABLE IF NOT EXISTS employer_topups (
    id VARCHAR(36) PRIMARY KEY,
    employer_id VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    total_amount DECIMAL(15,2) NOT NULL,
    currency VARCHAR(3) DEFAULT 'BRL',
    employee_count INT,
    target_department_id VARCHAR(36),
    target_plan_id VARCHAR(36),
    target_wallet_type VARCHAR(50),
    requested_at TIMESTAMP NOT NULL,
    scheduled_for TIMESTAMP,
    processed_at TIMESTAMP,
    completed_at TIMESTAMP,
    is_recurring BOOLEAN DEFAULT FALSE,
    recurrence_pattern VARCHAR(50),
    payment_method VARCHAR(50),
    payment_id VARCHAR(255),
    success_count INT DEFAULT 0,
    failure_count INT DEFAULT 0,
    failure_details TEXT,
    notes TEXT,
    created_by VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    INDEX idx_employer_topups (employer_id),
    INDEX idx_topup_status (status)
);

CREATE TABLE IF NOT EXISTS employer_policies (
    id VARCHAR(36) PRIMARY KEY,
    employer_id VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    type VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    daily_limit DECIMAL(15,2),
    monthly_limit DECIMAL(15,2),
    transaction_limit DECIMAL(15,2),
    requires_approval BOOLEAN DEFAULT FALSE,
    approval_levels INT DEFAULT 1,
    approver_roles TEXT,
    allowed_wallet_types TEXT,
    restricted_merchant_categories TEXT,
    target_departments TEXT,
    target_plans TEXT,
    allowed_time_slots TEXT,
    require_geolocation BOOLEAN DEFAULT FALSE,
    allowed_locations TEXT,
    created_by VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_by VARCHAR(255),
    updated_at TIMESTAMP,
    INDEX idx_employer_policies (employer_id),
    INDEX idx_policy_type (type)
);

-- ========== ADMIN-BFF ==========
CREATE TABLE IF NOT EXISTS audit_logs (
    id VARCHAR(36) PRIMARY KEY,
    tenant_id VARCHAR(255) NOT NULL,
    action VARCHAR(100) NOT NULL,
    entity_type VARCHAR(100) NOT NULL,
    entity_id VARCHAR(255),
    user_id VARCHAR(255) NOT NULL,
    user_name VARCHAR(255),
    user_role VARCHAR(100),
    before_data TEXT,
    after_data TEXT,
    metadata TEXT,
    ip_address VARCHAR(45),
    user_agent TEXT,
    request_id VARCHAR(255),
    timestamp TIMESTAMP NOT NULL,
    severity VARCHAR(20),
    outcome VARCHAR(20),
    index_key VARCHAR(500) NOT NULL,
    INDEX idx_audit_tenant (tenant_id),
    INDEX idx_audit_action (action),
    INDEX idx_audit_timestamp (timestamp),
    INDEX idx_audit_index_key (index_key)
);

CREATE TABLE IF NOT EXISTS system_configs (
    id VARCHAR(36) PRIMARY KEY,
    tenant_id VARCHAR(255),
    config_key VARCHAR(255) NOT NULL UNIQUE,
    config_value TEXT NOT NULL,
    data_type VARCHAR(50),
    description TEXT,
    category VARCHAR(100),
    is_encrypted BOOLEAN DEFAULT FALSE,
    is_editable BOOLEAN DEFAULT TRUE,
    validation_rule TEXT,
    version INT DEFAULT 1,
    previous_value TEXT,
    created_by VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_by VARCHAR(255),
    updated_at TIMESTAMP,
    INDEX idx_config_category (category),
    INDEX idx_config_tenant (tenant_id)
);

CREATE TABLE IF NOT EXISTS system_alerts (
    id VARCHAR(36) PRIMARY KEY,
    tenant_id VARCHAR(255),
    type VARCHAR(50) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    source VARCHAR(255) NOT NULL,
    title VARCHAR(500) NOT NULL,
    description TEXT NOT NULL,
    stack_trace TEXT,
    metadata TEXT,
    status VARCHAR(50) NOT NULL,
    assigned_to VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    acknowledged_at TIMESTAMP,
    acknowledged_by VARCHAR(255),
    resolved_at TIMESTAMP,
    resolved_by VARCHAR(255),
    resolution TEXT,
    notification_sent BOOLEAN DEFAULT FALSE,
    notification_sent_at TIMESTAMP,
    INDEX idx_alert_status (status),
    INDEX idx_alert_severity (severity),
    INDEX idx_alert_created (created_at)
);

CREATE TABLE IF NOT EXISTS tenant_management (
    id VARCHAR(36) PRIMARY KEY,
    tenant_id VARCHAR(255) NOT NULL UNIQUE,
    company_name VARCHAR(255) NOT NULL,
    cnpj VARCHAR(20) NOT NULL UNIQUE,
    status VARCHAR(50) NOT NULL,
    subscription_tier VARCHAR(50),
    onboarded_at TIMESTAMP NOT NULL,
    trial_ends_at TIMESTAMP,
    subscription_ends_at TIMESTAMP,
    max_users INT,
    max_transactions_per_month INT,
    current_user_count INT DEFAULT 0,
    current_transaction_count INT DEFAULT 0,
    primary_contact_name VARCHAR(255),
    primary_contact_email VARCHAR(255),
    primary_contact_phone VARCHAR(20),
    billing_email VARCHAR(255),
    billing_address TEXT,
    payment_method VARCHAR(50),
    enabled_features TEXT,
    custom_domain VARCHAR(255),
    logo_url VARCHAR(500),
    metadata TEXT,
    created_by VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_by VARCHAR(255),
    updated_at TIMESTAMP,
    INDEX idx_tenant_status (status),
    INDEX idx_tenant_tier (subscription_tier)
);

-- Continua no próximo bloco...
